# ff= []
# with open[path, 'r' , encoding='utf-8') as f:
#     for line in f:
#         ff.append[line.rstrip[))
# print[ff)
listword = [["aaa","111"],["bbb","222"],["ccc","333"],["ddd","444"],["eee","555"],["fff","666"],["ggg","777"],["hhh","888"],["iii","999"],["jjj","100"],["kkk","110"],["lll","120"],["mmm","130"]]
path1 = "3acoreplusaenglist.txt"
path2 = "3acoreplusaheblist.txt"
# Let's create a 2D list in Python containing the English and Hebrew words provided.
word_list = [
    ["addition", "תוספת, הוספה"],
    ["advance [n]", "התקדמות"],
    ["advanced", "מתקדם"],
    ["advertising", "פרסום"],
    ["among other things", "בין היתר"],
    ["analysis", "ניתוח, אנליזה"],
    ["appear", "להיראות, להופיע"],
    ["approach", "גישה, לגשת"],
    ["as", "כפי ש"],
    ["at least", "לפחות"],
    ["average", "ממוצע"],
    ["be responsible for", "להיות אחראי ל"],
    ["before", "לפני"],
    ["besides", "חוץ מ"],
    ["can", "יכול, פחית"],
    ["challenge", "לאתגר, אתגר"],
    ["chance", "סיכוי, הזדמנות"],
    ["change", "לשנות, להחליף"],
    ["characteristic", "מאפיין, תכונה"],
    ["characterize", "לאפיין, לתאר"],
    ["claim", "לטעון, טענה"],
    ["common", "נפוץ"],
    ["complicated", "מסובך, מורכב"],
    ["concern", "דאגה, עניין, לדאוג"],
    ["conditions", "תנאים, מצבים"],
    ["conduct", "לערוך"],
    ["consequence", "תוצאה, השלכה"],
    ["considerable", "ניכר, חשוב"],
    ["cope", "להתמודד"],
    ["critic", "מבקר [ביקורת]"],
    ["current", "נוכחי"],
    ["decrease", "להפחית, ירידה"],
    ["delayed [adj.]", "מעוכב"],
    ["deliberately", "בכוונה תחילה"],
    ["demonstrate", "להפגין, להדגים"],
    ["design", "לעצב, עיצוב"],
    ["destruction", "הרס, חורבן"],
    ["development", "פיתוח, התפתחות"],
    ["disagreement", "חוסר הסכמה"],
    ["disaster", "אסון"],
    ["discovery", "תגלית, גילוי"],
    ["dislike", "לא לאהוב"],
    ["doubt", "להטיל ספק, ספק"],
    ["drop", "להפיל, טיפה"],
    ["educate", "לחנך, ללמד"],
    ["efficient", "יעיל"],
    ["emphasis", "דגש, הדגשה"],
    ["enjoyable", "מהנה"],
    ["essay", "חיבור"],
    ["essentially", "בעיקרו, במהותו"],
    ["even if", "אפילו אם"],
    ["even though", "למרות ש"],
    ["event", "אירוע, מאורע"],
    ["exactly", "בדיוק"],
    ["except that", "אלא ש"],
    ["exist", "להיות קיים"],
    ["extraordinary", "יוצא מן הכלל, יוצא דופן"],
    ["feature", "מאפיין"],
    ["feedback", "משוב,ביקורת"],
    ["figure [n]", "דמות"],
    ["financial", "כספי"],
    ["findings", "ממצאים"],
    ["flexible", "גמיש"],
    ["flood", "שיטפון, הצפה, להציף, לעלות על גדותיו"],
    ["flu", "שפעת"],
    ["focus on/upon", "להתמקד ב"],
    ["focus", "מיקוד"],
    ["frequent", "תדיר, תכוף"],
    ["fresh", "טרי, רענן, חצוף"],
    ["frighten", "להפחיד"],
    ["gain", "להרוויח, להשיג"],
    ["generate", "ליצור, לחולל"],
    ["guidance", "הנחיה, הכוונה, הנהגה"],
    ["hopefully", "בתקווה"],
    ["ideal", "אידיאלי, מושלם"],
    ["illness", "חולי, מחלה"],
    ["illustrate", "להדגים, להמחיש, לאייר"],
    ["image", "דמות, תמונה"],
    ["in terms of", "במונחים של, מבחינת"],
    ["in actual fact", "למעשה"],
    ["in connection with", "בקשר ל"],
    ["in that case", "במקרה הזה"],
    ["in the meantime, meanwhile", "בינתיים"],
    ["initial", "התחלתי, ראשוני"],
    ["instruction", "הוראה"],
    ["interest", "עניין, ריבית"],
    ["introduce", "להציג, לערוך היכרות"],
    ["invest", "להשקיע"],
    ["investigate", "לחקור, לבדוק, לבחון"],
    ["just about", "כמעט, פחות או יותר"],
    ["keep on doing something", "להמשיך לעשות משהו"],
    ["kind of", "סוג של"],
    ["knowledge", "ידע"],
    ["lack", "לחסור"],
    ["landscape", "נוף"],
    ["likely", "סביר להניח"],
    ["limited", "מוגבל"],
    ["little", "קצת, מעט"],
    ["low", "נמוך"]
]
additional_words = [
    ["material", "חומר, בד"],
    ["mean", "להתכוון, מרושע"],
    ["means", "אמצעים"],
    ["measure", "למדוד, מידה"],
    ["mention", "לציין, להזכיר"],
    ["misunderstand", "להבין לא נכון"],
    ["more or less", "פחות או יותר"],
    ["naturally", "באופן טבעי"],
    ["nature", "טבע"],
    ["necessarily", "בהכרח"],
    ["nevertheless", "אף על פי כן"],
    ["not at all", "בכלל לא"],
    ["notice", "הודעה, להבחין"],
    ["objective", "מטרה, תכלית, אובייקטיבי"],
    ["occasional", "מדי פעם, מקרי"],
    ["official", "רשמי"],
    ["on the one hand, on the other hand", "מצד אחד...מצד שני"],
    ["once", "פעם"],
    ["others", "אחרים"],
    ["otherwise", "אחרת"],
    ["out of date", "לא מעודכן"],
    ["participate", "להשתתף ב"],
    ["particular", "מסוים"],
    ["perform", "להופיע, לבצע"],
    ["personality", "אישיות, אופי"],
    ["personally", "באופן אישי"],
    ["planet", "כוכב לכת"],
    ["planning", "תכנון"],
    ["plant", "צמח"],
    ["point of view", "נקודת מבט, השקפה"],
    ["policy", "מדיניות"],
    ["pollution", "זיהום סביבתי"],
    ["population", "אוכלוסיה"],
    ["prevent", "למנוע"],
    ["priority", "עדיפות"],
    ["private", "פרטי/אישי"],
    ["probable", "סביר, הגיוני"],
    ["produce", "לייצר"],
    ["profession", "מקצוע"],
    ["proof", "הוכחה, ראיה"],
    ["proposed [adj]", "מוצע"],
    ["protest", "למחות, מחאה"],
    ["provided [that]", "בתנאי ש"],
    ["public", "ציבור, ציבורי"],
    ["purpose", "כוונה, מטרה"],
    ["quality", "איכות, תכונה"],
    ["question", "להטיל ספק, שאלה"],
    ["questionnaire", "שאלון"],
    ["react", "להגיב, לענות"],
    ["reasonable", "סביר, הגיוני"],
    ["recommend", "להמליץ"],
    ["recycle", "למחזר"],
    ["regard", "להתייחס, להחשיב"],
    ["region", "אזור"],
    ["regular", "רגיל"],
    ["reliable", "אמין"],
    ["rely on", "לסמוך על"],
    ["request", "לבקש, בקשה"],
    ["research", "לחקור, מחקר"],
    ["result", "תוצאה"],
    ["review", "ביקורת, לחזור על"],
    ["revise", "לתקן, לשפר"],
    ["risk", "סיכון, לסכן"],
    ["run out of", "נגמר"],
    ["rural", "כפרי"],
    ["salary", "משכורת"],
    ["sample", "לדגום, דוגמה, מדגם"],
    ["seldom", "לעיתים רחוקות"],
    ["sense", "לחוש, להרגיש, חוש, הרגשה"],
    ["set up", "להקים"],
    ["significant", "משמעותי"],
    ["skilled", "מוכשר"],
    ["slight", "מעט"],
    ["specialist", "מומחה"],
    ["specific", "מסוים"],
    ["still", "עדיין"],
    ["structure", "מבנה"],
    ["study", "מחקר, לחקור"],
    ["supposed", "אמור ל"],
    ["surface", "פני השטח"],
    ["take advantage of", "לנצל"],
    ["thanks to", "הודות ל"],
    ["transport", "תחבורה"],
    ["trash", "זבל"],
    ["treatment", "טיפול, יחס"],
    ["unfortunately", "לרוע המזל"],
    ["unhealthy", "לא בריא"],
    ["unique", "ייחודי"],
    ["united", "מאוחד"],
    ["universe", "יקום, עולם"],
    ["unknown", "לא ידוע"],
    ["unlike", "שלא כמו, בניגוד ל"],
    ["unlikely", "לא סביר"],
    ["urban", "עירוני"],
    ["vary", "להשתנות, להיות מגוון"],
    ["view", "נוף"],
    ["visible", "נראה לעין"],
    ["vision", "ראייה, חזון"],
    ["whom", "מי, ש"],
    ["wildlife", "חיות בר, טבע"],
    ["within", "בתוך"],
    ["worthwhile", "כדאי, משתלם"],
    ["emphasize", "להדגיש, להבליט"],
    ["analyze", "לנתח"],
    ["appearance", "מראה חיצוני, הופעה"],
    ["on average", "בממוצע"],
    ["characterize", "לאפיין, לתאר"],
    ["complicate", "לסבך"],
    ["concerned", "מודאג, מוטרד"],
    ["concerning", "בנוגע ל"],
    ["concerned with", "עוסק ב"],
    ["consequently", "כתוצאה"],
    ["criticize", "להעביר ביקורת"],
    ["criticism", "ביקורת"],
    ["currently", "כרגע, נכון לעכשיו"],
    ["deliberate", "מכוון"],
    ["demonstration", "הוכחה, הפגנה, הדגמה"],
    ["designer", "מעצב"],
    ["developing", "מתפתח"],
    ["developed", "מפותח"],
    ["educated", "משכיל, מחונך"],
    ["educator", "איש חינוך"],
    ["Efficiency", "יעילות"],
    ["efficiently", "ביעילות"],
    ["emphasize", "להדגיש, להבליט"],
    ["enjoyment", "הנאה"],
    ["existence", "קיום, מציאות"],
    ["figure out", "להבין, לקלוט"],
    ["finance", "לממן, מימון"],
    ["Flexibility", "גמישות"],
    ["Frequency", "תדירות"],
    ["hopeful", "מלא תקווה"],
    ["illustration", "איור, הדגמה, המחשה"],
    ["initially", "בהתחלה"],
    ["interested in", "מעוניין ב"],
    ["investor", "משקיע ב"],
    ["investment", "השקעה"],
    ["investigation", "חקירה"],
    ["investigator", "חוקר"],
    ["limitation", "מגבלה, הגבלה"],
    ["meaning", "משמעות, פירוש"],
    ["occasionally", "מדי פעם, לפעמים"],
    ["old-fashioned", "מיושן"],
    ["participant", "משתתף"],
    ["participation", "השתפות"],
    ["particularly", "במיוחד"],
    ["performance", "ביצוע, הופעה"],
    ["planned", "מתוכנן"],
    ["pollute", "לזהם"],
    ["Prevention", "מניעה, עיכוב"],
    ["Producer", "מפיק"],
    ["professional", "מקצועי"],
    ["publicly", "בפומבי"],
    ["reaction", "תגובה"],
    ["reasonably", "באופן הגיוני/סביר"],
    ["recommendation", "המלצה"],
    ["regardless", "למרות, ללא קשר"],
    ["regarding", "בנוגע ל"],
    ["regional", "אזורי"],
    ["researcher", "חוקר"],
    ["resulting", "שנגרם מ"]
]
additional_words_2 = [
    ["above", "מעל, למעלה"],
    ["account", "חשבון"],
    ["acquire", "לרכוש"],
    ["age", "גיל, תקופה, עידן"],
    ["agriculture", "חקלאות"],
    ["all of a sudden", "פתאום"],
    ["altogether", "בסך הכל, לגמרי"],
    ["anxious", "חרד, מודאג, משתוקק"],
    ["apparent", "גלוי, נראה"],
    ["appropriate", "הולם, מתאים"],
    ["atmosphere", "אווירה"],
    ["be in charge", "להיות אחראי"],
    ["[be] situated", "להיות ממוקם"],
    ["blame", "להאשים, אשמה"],
    ["block", "לחסום"],
    ["brilliant", "מבריק / מצויין"],
    ["bring up", "להעלות נושא/ לגדל ילדים"],
    ["calculate", "לחשב"],
    ["clothing", "ביגוד"],
    ["competitive", "תחרותי"],
    ["contemporary", "עכשווי"],
    ["contest", "תחרות"],
    ["continent", "יבשת"],
    ["criterion", "מדד"],
    ["cut down", "לכרות, לקצץ"],
    ["decade", "עשור שנים"],
    ["declare", "להכריז, להצהיר"],
    ["degree", "תואר, מעלה"],
    ["deliver", "למסור, להעביר"],
    ["demanding", "תובעני"],
    ["detect", "לאתר"],
    ["determine", "לקבוע, להחליט"],
    ["differ", "להיות שונה"],
    ["disappointed", "מאוכזב"],
    ["divide", "לחלק, לפצל"],
    ["domestic", "ביתי"],
    ["done", "עשוי, גמור"],
    ["double", "להכפיל, כפול"],
    ["economic", "כלכלי"],
    ["editor", "עורך"],
    ["either way", "בכל מקרה"],
    ["element", "יסוד, אלמנט, רכיב"],
    ["emerge", "לצאת מתוך, להתגלות"],
    ["emotion", "רגש"],
    ["exception", "יוצא דופן, יוצא מהכלל"],
    ["exchange", "להמיר, להחליף, המרה, החלפה"],
    ["expected", "צפוי"],
    ["expedition", "משלחת, מסע"],
    ["expense", "(הוצאה (מחיר"],
    ["export", "לייצא, ייצוא"],
    ["expression", "הבעה, ביטוי"],
    ["extend", "להאריך, להרחיב"],
    ["extreme", "קיצוני"],
    ["farther, further", "רחוק יותר"],
    ["fed up", "נמאס"],
    ["fetch", "להביא"],
    ["final", "סופי, אחרון"],
    ["fit [adj]", "בכושר, מתאים"],
    ["generation", "דור"],
    ["genuine", "אמיתי, מקורי"],
    ["get rid of", "להיפטר מ"],
    ["get something wrong", "לטעות"],
    ["get worse", "להיות גרוע יותר, להחמיר"],
    ["give away", "לתרום, לתת"],
    ["hidden", "מוסתר"],
    ["highlight", "להדגיש"],
    ["identical", "זהה"],
    ["immigration", "הגירה"],
    ["import", "לייבא, יבוא"],
    ["impression", "רושם"],
    ["incredible", "מדהים"],
    ["indoors", "בפנים"],
    ["input", "קלט"],
    ["infection", "זיהום, דלקת"],
    ["interaction", "אינטראקציה, פעולת גומלין"],
    ["interpret", "לפרש"],
    ["interrupt", "להפריע, לקטוע בדיבור"],
    ["involvement", "מעורבות"],
    ["issue", "נושא, סוגיה"],
    ["it looks like/ as if/ as though", "זה נראה כמו"],
    ["jam", "ריבה, פקק תנועה"],
    ["journalist", "עיתונאי"],
    ["judgement", "שיפוט"],
    ["just as", "בדיוק כמו"],
    ["justice", "צדק"],
    ["keen", "נלהב"],
    ["keep", "לשמור, להמשיך"],
    ["kit", "ערכה"],
    ["lecture", "הרצאה"],
    ["light", "אור, קל, בהיר"],
    ["living", "חי, פרנסה"],
    ["logical", "הגיוני"],
    ["look forward to", "לצפות ל"],
    ["lower", "להנמיך"],
    ["make sense", "להיות הגיוני"],
    ["make up", "להמציא / להשלים / איפור"],
    ["make up your mind", "לקבל החלטה"],
    ["mend", "לתקן"],
    ["mixture", "תערובת"],
    ["monthly", "חודשי"],
    ["mystery", "תעלומה"],
    ["native", "יליד, מקומי"],
    ["neither ... nor", "לא... ולא"],
    ["nightmare", "סיוט, חלום בלהות"],
    ["nonsense", "שטויות"],
    ["not until", "לא עד..."],
    ["occupation", "מקצוע, עיסוק"],
    ["occupy", "ליישב, להעסיק"],
    ["oil", "שמן"],
    ["on the whole", "באופן כללי"],
    ["operate", "להפעיל, לנתח"],
    ["organ", "איבר, אורגן"],
    ["organization", "ארגון"],
    ["outstanding", "יוצא מהכלל, יוצא דופן"],
    ["part-time [job]", "משרה חלקית"],
    ["patient", "סבלני, מטופל"],
    ["peculiar", "מוזר"],
    ["point", "נקודה, להצביע"],
    ["position", "עמדה, תפקיד"],
    ["potential", "יכולת, פוטנציאל"],
    ["preference", "העדפה"],
    ["present [v]", "להציג"],
    ["pressure", "לחץ"],
    ["prime", "ראשוני, עיקרי"],
    ["principal", "מנהל בית ספר, עיקרי"],
    ["promote", "לקדם, להעלות"],
    ["put up with", "לסבול, לשאת, להתמודד עם"],
    ["reach", "להגיע, להשיג"],
    ["reason", "הגיון, סיבה"],
    ["record", "להקליט, שיא, תקליט"],
    ["reflect", "לשקף, להרהר"],
    ["register", "להירשם"],
    ["regret", "להתחרט, חרטה"],
    ["relate", "לספר, לייחס"],
    ["relax", "להירגע"],
    ["remark", "להעיר הערה/הערה"],
    ["remote", "מרוחק"],
    ["replace", "להחליף, לשנות"],
    ["rescue", "לחלץ, חילוץ"],
    ["respect", "כבוד, לכבד"],
    ["retire", "לפרוש מן העבודה"],
    ["right", "ימין, נכון, צודק, זכות"],
    ["role", "תפקיד"],
    ["rule", "לשלוט, חוק"],
    ["run", "לנהל/לרוץ"],
    ["rush", "למהר/בהילות"],
    ["satisfy", "לספק, להשביע רצון"],
    ["scale", "קנה מידה, היקף, דירוג"],
    ["scene", "סצנה, זירה"],
    ["schedule", "לוח זמנים"],
    ["sensitive", "רגיש"],
    ["service", "שירות"],
    ["set", "לערוך, לקבוע"],
    ["setting", "מקום וזמן"],
    ["shortly", "בקיצור, בקרוב"],
    ["shut down", "לסגור, לכבות"],
    ["slow down", "להאט"],
    ["so-called", "כביכול"],
    ["society", "חברה [של אנשים], אגודה"],
    ["sooner or later", "במוקדם או במאוחר"],
    ["spectacular", "מרהיב"],
    ["speech", "נאום, דיבור"],
    ["spoil", "לקלקל, לפנק"],
    ["start off", "להתחיל, להיפתח ב..."],
    ["style", "סגנון, אופנה"],
    ["sum up", "לסכם, סיכום"],
    ["summary", "סיכום"],
    ["support", "לתמוך, תמיכה"],
    ["survive", "לשרוד"],
    ["take into account", "לקחת בחשבון"],
    ["take part", "להשתתף ב"],
    ["take place", "להתרחש"],
    ["take the opportunity to", "לנצל את ההזדמנות ל.."],
    ["take.... seriously", "לקחת.... ברצינות"],
    ["take/accept/claim responsibility for sth", "לקחת אחריות על"],
    ["the headlines", "כותרות בעיתון"],
    ["the heart of..", "...לב ה"],
    ["the main thing", "הדבר העיקרי"],
    ["the reality of..", "...המציאות של"],
    ["theme", "נושא מרכזי"],
    ["treasure", "אוצר, מטמון"],
    ["try", "נסיון, לנסות"],
    ["turn [n]", "תור"],
    ["[un]comfortable", "לא (נוח)"],
    ["underneath", "מתחת ל"],
    ["understand", "להבין"],
    ["undo", "לפרום, לבטל, להחזיר לקדמותו"],
    ["unemployed", "מובטל"],
    ["unexpected", "לא צפוי"],
    ["up-to-date", "עדכני, מעודכן"],
    ["urgent", "דחוף"],
    ["use up", "להשתמש עד תום"],
    ["virtual reality", "מציאות מדומה"],
    ["vowel", "אות ניקוד"],
    ["waste", "לבזבז, בזבוז"],
    ["wealth", "עושר"],
    ["welcome", "לקדם בברכה, ברוך הבא"],
    ["wherever", "בכל מקום, לא משנה היכן"],
    ["aquisition", "רכישה"],
    ["aged", "זקן, קשיש, מיושן"],
    ["agricultural", "חקלאי (תואר)]"],
    ["anxiety", "חרדה, דאגה"],
    ["apparently", "ככל הנראה, לכאורה"],
    ["calculator", "מחשבון"],
    ["competitor", "מתחרה"],
    ["declaration", "הצהרה, הכרזה"],
    ["disappointment", "אכזבה"],
    ["division", "חלוקה, מחלקה (צבאית)]"],
    ["emotional", "רגשי"],
    ["at the expense of", "על חשבון"],
    ["semi-final", "חצי גמר"],
    ["Fitness", "כושר גופני"],
    ["immigrant", "מהגר"],
    ["impressive", "מרשים"],
    ["incredibly [adv]", "באופן מדהים"],
    ["interact", "לתקשר"],
    ["interruption", "הפרעה, הפסקה"],
    ["involved", "מעורב ב"],
    ["involve", "לערב"],
    ["traffic jam", "פקק תנועה"],
    ["just", "כרגע, זה עתה, רק, צודק, הגון"],
    ["lecture", "הרצאה"],
    ["in light of", "לאור, לנוכח"],
    ["mysterious", "מסתורי"],
    ["native language", "שפת אם, שפה ילידית"],
    ["occupied", "תפוס, כבוש, עסוק"],
    ["operation", "ניתוח, פעולה, מבצע"],
    ["patience", "סבלנות"],
    ["promotion", "קידום, העלאה בדרגה"],
    ["Reflection", "השתקפות, הרהור"],
    ["registration", "רישום, הרשמה"],
    ["related", "קשור ל"],
    ["relative", "יחסי, קרוב משפחה"],
    ["replacement", "תחליף"],
    ["respectable", "מעורר כבוד, מכובד"],
    ["retired", "פרש לגמלאות"],
    ["roughly", "בערך, בגסות"],
    ["satisfactory", "משביע רצון, מספק"],
    ["scenery", "נוף, תפאורה"],
    ["Sensitivity", "רגישות"],
    ["serve", "לשרת, להגיש"],
    ["set", "לערוך, לקבוע"],
    ["social", "חברתי, סוציאלי, אירוע חברתי"],
    ["supporter", "תומך"],
    ["survival", "הישרדות"],
    ["survivor", "שורד, ניצול"],
    ["urgently", "באופן דחוף"],
    ["wealthy", "עשיר"]
]
d = len(word_list)
# with open(path1, 'a') as file1: 
#       for i in range(d):
#          file1.write(word_list[i][0] + "\n") 
with open(path2, 'a') as file1:  
       for i in range(d):
          g = word_list[i][1]
          g = g[::-1]
          file1.write(g + "\n") 

d = len(additional_words)
# with open(path1, 'a') as file1: 
#        for i in range(d):
#          file1.write(additional_words[i][0] + "\n") 
with open(path2, 'a') as file1:  
       for i in range(d):
         g = additional_words[i][1]
         g = g[::-1]
         file1.write(g + "\n")

d = len(additional_words_2)
# with open(path1, 'a') as file1: 
#       for i in range(d):
#          file1.write(additional_words_2[i][0] + "\n") 
with open(path2, 'a') as file1:  
      for i in range(d):
        g = additional_words_2[i][1]
        g = g[::-1]
        file1.write(g + "\n")
# with open(path2, 'r') as file1:
#     lines = file1.readlines()
#     for line in lines:
#         print(line)